### PR TITLE
Update badges and formatting

### PR DESCRIPTION
**Pull request by atouchet**
- Replace Travis CI badge with GitHub Actions and remove references
- Fix crates.io badge
- Update some formatting and use HTTPS for links

- [x] I agree to follow the project's [code of conduct](https://github.com/georust/geo/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

**Comment by lnicola** [comment]
Thanks, looks good. Do you think a docs.rs badge would be useful? I like them, but a lot of projects do without. Something like:

```md
[![API docs]][docs.rs]

[API docs]: https://docs.rs/tilejson/badge.svg
[docs.rs]: https://docs.rs/tilejson/
```

**Comment by atouchet** [comment]
Either option seems fine to me. Do you want a docs.rs badge added?

**Comment by lnicola** [comment]
I only have commit rights here incidentally.

r? @stepankuzmin

**Comment by stepankuzmin** [comment]
Yep, that would be great, thanks!

**Comment by atouchet** [comment]
Okay I've added a docs badge.

**Review by lnicola — APPROVED** [review]

**Pull request merged**
